# .travis.yml for cartogram.
language: r

matrix:
  include:
    - dist: trusty
      r: oldrel      
    - os: osx
      osx_image: xcode9.4
      disable_homebrew: true
      before_install:
      r: 
        - release
        - devel
      

r:
  - release
  - devel

cache: packages
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # sf dependencies:
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
        
apt_packages:
  - libgdal-dev
  - libproj-dev

notifications:
email:
on_success: change
on_failure: change
